// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmumpwimnxaesjkkccnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdW1wd2ltbnhhZXNqa2tjY25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzQxNTcsImV4cCI6MjA2MjcxMDE1N30.B9y4hbbgwfZWFO_PpKeHPIKShSHE1noSuKpX4VwsfLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);